### ISSUE TITLE
thank you screen, second button for showing results

### ISSUE THREAD

**Issue by Gr1ll** [danieljancar/votevault#35]
### Package

- [x] `frontend`
- [ ] `contracts`
- [ ] `architecture`
- [ ] `documentation`
- [ ] `Other`

## Expected Behavior

show second button for instantly showing results to voting instead of going to homepage first and having to reenter voteId.

## Actual Behavior

need to click on home button first, after reload all the data.

**Comment by danieljancar** [comment]
I think you mean the success banner on `create.component` right? How about we remove the button and add "View Vote" with going to `voting/:id`? 🤓
